# Generated by Django 4.2.20 on 2025-04-19 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('original', 'Original Article'), ('review', 'Review Article')], max_length=20)),
                ('submission_date', models.DateField()),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('under_review', 'Under review'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='under_review', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
