# Generated by Django 4.2.20 on 2025-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload your article as a PDF file', null=True, upload_to='article_pdfs/'),
        ),
    ]
