# Generated by Django 4.2.20 on 2025-04-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0004_article_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('minor_corrections', 'Minor Corrections'), ('major_corrections', 'Major Corrections')], max_length=20)),
                ('comments', models.TextField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='journal.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['article', 'reviewer', '-revision'],
                'unique_together': {('article', 'reviewer', 'revision')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewing_articles', through='journal.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
