# Generated by Django 4.2.20 on 2025-04-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_review_article_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('minor_corrections', 'Minor Corrections'), ('major_corrections', 'Major Corrections')], default='new', max_length=20),
        ),
    ]
