# Generated by Django 4.2.20 on 2025-04-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_review_comments_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='current_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('under_review', 'Under review'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='under_review', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('revised_pdf', models.FileField(blank=True, null=True, upload_to='revised_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='journal.article')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_responses', to='journal.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
