# Generated by Django 4.2.20 on 2025-04-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_article_current_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
