# Generated by Django 5.1.5 on 2025-04-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_submission_review_submissionfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("revision_required", "Revision Required"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
