# Generated by Django 5.1.5 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_alter_submission_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfile",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
