# Generated by Django 5.1.5 on 2025-04-23 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_submissionfile_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionfile",
            name="submission",
        ),
        migrations.AddField(
            model_name="submissionfile",
            name="review",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="portal.review",
            ),
            preserve_default=False,
        ),
    ]
