# Generated by Django 5.1.5 on 2025-04-24 02:45

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_remove_submissionfile_submission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewInvitation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, default=portal.models.default_due_date, null=True
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="portal.review",
                    ),
                ),
            ],
        ),
    ]
