# Generated by Django 5.1.5 on 2025-04-24 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_reviewer_delete_reviewinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
