# Generated by Django 4.2.18 on 2025-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the affiliation', max_length=255)),
                ('address', models.TextField(help_text='Full address of the affiliation')),
                ('country', models.CharField(help_text='Country where the affiliation is located', max_length=100)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=50)),
            ],
            options={
                'verbose_name': 'Affiliation',
                'verbose_name_plural': 'Affiliations',
            },
        ),
    ]
