# Generated by Django 5.1.5 on 2025-04-20 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_author_delete_affiliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("institution", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("street_address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "zip_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("country_region", models.CharField(max_length=100)),
                (
                    "address_is_for",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available_as_reviewer", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select a title"),
                            ("dr", "Dr."),
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("prof", "Prof."),
                            ("rev", "Rev."),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select a degree"),
                            ("phd", "PhD"),
                            ("md", "MD"),
                            ("jd", "JD"),
                            ("mba", "MBA"),
                            ("ma", "MA"),
                            ("ms", "MS"),
                            ("ba", "BA"),
                            ("bs", "BS"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("primary_phone", models.CharField(max_length=20)),
                (
                    "primary_phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("assistant", "Assistant"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "secondary_phone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("assistant", "Assistant"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
